name: Infinite High-Speed RDP Runner

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"  # Auto restart every 6 hours

jobs:
  rdp-session:
    runs-on: windows-latest
    timeout-minutes: 350

    steps:
      - name: Enable RDP + Create Permanent User
        shell: pwsh
        run: |
          Write-Host "Enabling RDP..."
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' `
            -Name "fDenyTSConnections" -Value 0 -Force
          netsh advfirewall firewall add rule name="RDP" dir=in action=allow protocol=TCP localport=3389

          $password = "M@zharas12"  # Permanent password
          $securePass = ConvertTo-SecureString $password -AsPlainText -Force

          if (-not (Get-LocalUser -Name "RDP" -ErrorAction SilentlyContinue)) {
            New-LocalUser -Name "RDP" -Password $securePass -AccountNeverExpires
            Add-LocalGroupMember -Group "Administrators" -Member "RDP"
            Add-LocalGroupMember -Group "Remote Desktop Users" -Member "RDP"
          } else {
            Write-Host "User already exists."
          }

          Write-Host "✅ Username: RDP"
          Write-Host "✅ Password: $password"

      - name: Install and Connect Tailscale
        shell: pwsh
        run: |
          Write-Host "Installing Tailscale..."
          $tsInstaller = "$env:TEMP\tailscale.exe"
          Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe" -OutFile $tsInstaller
          Start-Process -FilePath $tsInstaller -ArgumentList "/quiet" -Wait
          $tsExe = "C:\Program Files\Tailscale\tailscale.exe"
          & "$tsExe" up --authkey "${{ secrets.TAILSCALE_AUTHKEY }}" --hostname "GitHub-Runner-${{ github.run_id }}"
          Write-Host "✅ Tailscale connection established."

      - name: Install ProtonVPN via Winget
        shell: pwsh
        run: |
          Write-Host "Installing ProtonVPN using Winget..."
          winget install --id=ProtonTechnologies.ProtonVPN --accept-package-agreements --accept-source-agreements -h
          Write-Host "✅ ProtonVPN Installed Successfully via Winget."

      # Optional: uncomment this section if you want auto-login later
      # - name: Auto Login ProtonVPN (optional)
      #   shell: pwsh
      #   run: |
      #     $protonPath = "C:\Program Files\Proton Technologies\ProtonVPN\ProtonVPN.exe"
      #     if (Test-Path $protonPath) {
      #       Write-Host "Logging into ProtonVPN..."
      #       Start-Process -FilePath $protonPath -ArgumentList "cli", "login", "${{ secrets.PROTON_USER }}", "${{ secrets.PROTON_PASS }}" -Wait
      #       Write-Host "✅ ProtonVPN login completed."
      #     } else {
      #       Write-Host "⚠️ ProtonVPN not found."
      #     }

      - name: Display RDP Details
        shell: pwsh
        run: |
          Write-Host "========== RDP ACCESS =========="
          Write-Host "Use Tailscale IP from your Tailscale dashboard"
          Write-Host "Username: RDP"
          Write-Host "Password: M@zharas12"
          Write-Host "================================"
          Write-Host "ProtonVPN is preinstalled and ready to use."

      - name: Keep Alive
        shell: pwsh
        run: |
          for ($i=0; $i -lt 350; $i+=5) {
            Write-Host "[$(Get-Date)] RDP Active for $i minutes..."
            Start-Sleep -Seconds 300
          }

      - name: Auto Restart
        if: always()
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: restart-runner
